export const ADD_TO_WISH_LIST = "ADD_TO_WISH_LIST";
export const GET_USER_WISHLIST = "GET_USER_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const REMOVE_WISHLIST = "REMOVE_WISHLIST";
export const ADD_TEPM_WISH_ID = "ADD_TEPM_WISH_ID";
export const REMOVE_TEPM_WISH_ID = "REMOVE_TEPM_WISH_ID";
